apiVersion: apps/v1
kind: Deployment
metadata:
  name: unit-converter-deployment
spec:
  selector:
    matchLabels:
      app: unit-converter-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: unit-converter-backend
          image: unit_converter_backend
          ports:
            - containerPort: 8080
              name: server
